/*
    Attention: This file is generated by "reaux-cli", do not modify
*/
import { StateView } from 'reaux-dom';

import { State as AboutState } from 'src/modules/about/type';
import { State as HomeState } from 'src/modules/home/type';
import { State as MainState } from 'src/modules/main/type';

export interface AllState extends StateView {
  about: AboutState;
  home: HomeState;
  main: MainState;
}
